### ISSUE TITLE
How to rotate 90 deg ?

### ISSUE THREAD

**Issue by janoist1** [RyanEwen/esphome-lvgl#14]
Hi,

Very nice work, thank you for sharing it.

I'm trying to rotate it from portrait to landscape without success. I've added `transform` and `rotation` as follows:

```
display:
  - id: main_display
    platform: qspi_dbi
    dimensions:
      height: 480
      width: 320
    model: CUSTOM
    data_rate: 40MHz
    cs_pin:
      number: 45
      ignore_strapping_warning: true
    draw_from_origin: true
    update_interval: never
    auto_clear_enabled: false
    rotation: 90

touchscreen:
  - id: main_touchscreen
    platform: axs15231
    i2c_id: bus_touchscreen
    address: 0x3B
    transform:
       mirror_x: false
       mirror_y: true
       swap_xy: true
```

These made the screen looking good, however touch does not seem to be in sync properly. Have you got any idea please? Thanks
